export enum ServiceType {
    INITIAL_VACCINATION = 'INITIAL_VACCINATION',
    FIRST_FREE_BATH = 'FIRST_FREE_BATH',
    INITIAL_CHECKUP = 'INITIAL_CHECKUP',
    GROOMING = 'GROOMING',
    VACCINATION = 'VACCINATION',
    VETERINARY_CONSULTATION = 'VETERINARY_CONSULTATION',
    MEDICATION_ADMINISTRATION = 'MEDICATION_ADMINISTRATION',
}
